
export const DatiMock = [
    {
      id: 1,
      selected: false,
      codice: 1,
      descrizione: "Descrizione 1",
      data: new Date("2024-01-01"),
    },
    {
      id: 2,
      selected: false,
      codice: 2,
      descrizione: "Descrizione 2",
      data: new Date("2023-01-01"),
    },
    {
      id: 3,
      selected: false,
      codice: 3,
      descrizione: "Descrizione 3",
      data: new Date("2023-06-01"),
    },
    {
      id: 4,
      selected: false,
      codice: 6,
      descrizione: "Descrizione 4",
      data: new Date("2023-12-01"),
    },
    {
      id: 5,
      selected: false,
      codice: 1,
      descrizione: "Descrizione 1",
      data: new Date("2024-01-01"),
    },
    {
      id: 6,
      selected: false,
      codice: 2,
      descrizione: "Descrizione 2",
      data: new Date("2023-01-01"),
    },
    {
      id: 7,
      selected: false,
      codice: 3,
      descrizione: "Descrizione 3",
      data: new Date("2023-06-01"),
    },
    {
      id: 8,
      selected: false,
      codice: 6,
      descrizione: "Descrizione 4",
      data: new Date("2023-12-01"),
    },
    {
      id: 9,
      selected: false,
      codice: 1,
      descrizione: "Descrizione 1",
      data: new Date("2024-01-01"),
    },
    {
      id: 10,
      selected: false,
      codice: 2,
      descrizione: "Descrizione 2",
      data: new Date("2023-01-01"),
    },
    {
      id: 11,
      selected: false,
      codice: 3,
      descrizione: "Descrizione 3",
      data: new Date("2023-06-01"),
    },
    {
      id: 12,
      selected: false,
      codice: 6,
      descrizione: "Descrizione 4",
      data: new Date("2023-12-01"),
    },
    {
      id: 13,
      selected: false,
      codice: 1,
      descrizione: "Descrizione 1",
      data: new Date("2024-01-01"),
    },
    {
      id: 14,
      selected: false,
      codice: 2,
      descrizione: "Descrizione 2",
      data: new Date("2023-01-01"),
    },
    {
      id: 15,
      selected: false,
      codice: 3,
      descrizione: "Descrizione 3",
      data: new Date("2023-06-01"),
    },
    {
      id: 16,
      selected: false,
      codice: 6,
      descrizione: "Descrizione 4",
      data: new Date("2023-12-01"),
    },
    {
      id: 17,
      selected: false,
      codice: 1,
      descrizione: "Descrizione 1",
      data: new Date("2024-01-01"),
    },
    {
      id: 18,
      selected: false,
      codice: 2,
      descrizione: "Descrizione 2",
      data: new Date("2023-01-01"),
    },
    {
      id: 19,
      selected: false,
      codice: 3,
      descrizione: "Descrizione 3",
      data: new Date("2023-06-01"),
    },
    {
      id: 20,
      selected: false,
      codice: 6,
      descrizione: "Descrizione 4",
      data: new Date("2023-12-01"),
    },
    {
      id: 21,
      selected: false,
      codice: 1,
      descrizione: "Descrizione 1",
      data: new Date("2024-01-01"),
    },
    {
      id: 22,
      selected: false,
      codice: 2,
      descrizione: "Descrizione 2",
      data: new Date("2023-12-010"),
    },
    {
      id: 23,
      selected: false,
      codice: 3,
      descrizione: "Descrizione 3",
      data: new Date("2023-10-01"),
    },
    {
      id: 24,
      selected: false,
      codice: 6,
      descrizione: "Descrizione 4",
      data: new Date("2023-12-01"),
    },
    // Aggiungi altri dati secondo necessità
  ];
